### ISSUE TITLE
Read SSH tunnel configuration from file

### ISSUE THREAD

**Issue by jvandertil** [jvandertil/Tunnels#1]
The use case is that you can start the application and it will automatically connect to multiple servers and create SSH tunnels (possibly multiple per host) as configured.

Suggestion YAML configuration file:
```yaml
config:
  example.com:
    username: root
    keyFile: "id_rsa"
    local: 
      - 1234:localhost:9091 # Local 1234 to remote localhost:9091
      - 1337:localhost:1330
  more.example.com:
    username: test
    keyFile: "/usr/lib/test/id_rsa"
    local:
      - 9090:localhost:9091
      - 1234:example.com:1234
```
